### ISSUE TITLE
The examples now show a blank screen ( _h is not defined )

### ISSUE THREAD

**Issue by mwarren2** [Akryum/meteor-vue-component#93] opened 2016-12-19 12:44 UTC
I've been using the examples as templates -  they've been very helpful.

Unfortunately they now produce a blank screen in the browser, and my apps are all failing too.
The console reveals the following errors:

[Vue warn]: Error when rendering anonymous component
Uncaught ReferenceError: _h is not defined(…)

This happens with at least two of the examples:
1) Simple example project (Vue 2.x)
2) Routing example project (vue 2.x)

the error is in **vue.runtime.common.js**, at line 2952
```     vnode = render.call(vm._renderProxy, vm.$createElement);```

This line is called three times by the browser, and it's failing the second time.

it's failing in App.vue at the `return{` on line 12:

```
import Chat from './Chat.vue';
import {Session} from 'meteor/session';

Session.setDefault("counter", 0);

let labels = ['Click me!', 'Click me again!', 'Here! Click here!', 'Again! Again!',
'Don\'t click me! No, I\'m just kidding. You can.', 'You like that?',
'Can you stratch me in the back please?', 'You are soooo nice! Click!',
'Hmmmm...', 'You know, you are wasting time clicking me.',
'No really, you can click me as much as you want.', 'Click me to level up!'];

return {
  data() {
    return {
      buttonLabel: 'Click me!',
      count: 0
    }
  },
  meteor: {
    data: {
      count() {
        return Session.get('counter');
      }
    }
  },
  methods: {
    addOne() {
      Session.set('counter', this.count + 1);
      this.buttonLabel = labels[Math.round(Math.random()*(labels.length - 1))];
    }
  },
  components: {
    Chat,
  },
};
```

It's trying to find a handler here, and failing - `key` = '_h':
```
    var hasHandler = {
        has: function has (target, key) {
            var has = key in target;
            var isAllowed = allowedGlobals(key) || key.charAt(0) === '_';
            if (!has && !isAllowed) {
                warnNonPresent(target, key);
            }
            return has || !isAllowed
        }
    };
```

**Comment by Akryum** [comment] 2016-12-19 13:30
Duplicate of #92.

**Closed by Akryum** 2016-12-19 13:30 UTC
